language: python
dist: trusty

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        packages: 
        - g++-7
        - hdf5-tools
        - python3
    env: COMP_CC=gcc-7 && COMP_CXX=g++-7
    python: 3.6

  - os: linux
    compiler: clang
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages: 
        - clang-5.0
        - hdf5-tools
        - python3
    env: COMP_CC=clang-5.0 && COMP_CXX=clang++-5.0
    python: 3.6

  - os: osx
    osx_image: xcode10.1
    env: 
    - COMP_EVAL="brew update && brew install gcc hdf5 fftw fmt && COMP_CC=gcc-7 && COMP_CXX=g++-7"
    language: generic


before_install:
  - eval "${COMP_EVAL}"
  - eval "CC=${COMP_CC}"
  - eval "CXX=${COMP_CXX}"

script:
  - mkdir build && cd build 
  - cmake .. 
  - make

