language: python
dist: trusty

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        packages: 
        - g++-7
        - hdf5-tools
        - python3
        - libopenmpi3
    env: COMP_EVAL="CC=gcc-7 && COMP_CXX=g++-7"
    python: 3.6

  - os: linux
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages: 
        - clang-5.0
        - hdf5-tools
        - python3
        - libopenmpi3
    env: COMP_EVAL="CC=clang-5.0 && COMP_CXX=clang++-5.0"
    python: 3.6

  - os: osx
    osx_image: xcode10.1
    env: COMP_EVAL="brew update && brew install gcc hdf5 open-mpi fftw fmt && CC=gcc-8 && CXX=g++-8"
    language: generic


before_install:
  - eval "${COMP_EVAL}"


script:
  - $CXX --version
  - mkdir build && cd build 
  - cmake .. 
  - make

