language: cpp
os: 
    - linux
    - osx
compiler: 
    - gcc
    - clang

sudo: required
dist: trusty
language: cpp


matrix:
  include:
    - compiler: gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++7"
    - compiler: clang
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - compiler: gcc
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build && cd build 
    - cmake .. 
    - make

