language: python
dist: trusty

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        packages: 
        - g++-7
        - hdf5-tools
        - python3
        - libopenmpi-dev
    env: COMP_EVAL="COMP_CC=gcc-7 && COMP_CXX=g++-7"
    python: 3.6

  - os: linux
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages: 
        - clang-5.0
        - g++-7
        - hdf5-tools
        - python3
        - libopenmpi-dev
    env: COMP_EVAL="COMP_CC=clang-5.0 && COMP_CXX=clang++-5.0"
    python: 3.6

  - os: osx
    osx_image: xcode10.1
    env: COMP_EVAL="brew update && brew install gcc@7 hdf5 open-mpi fftw fmt && COMP_CC=gcc-7 && COMP_CXX=g++-7"
    language: generic


before_install:
  - eval "${COMP_EVAL}"

script:
  - export CC=${COMP_CC}
  - export CXX=${COMP_CXX}
  - $CXX --version
  - export MPI_COMPILE_FLAGS=$(mpicc --showme:compile)
  - export MPI_LINK_FLAGS=$(mpicc --showme:link)
  - echo $MPI_COMPILE_FLAGS
  - echo $MPI_LINK_FLAGS
  - export PATH=${PATH):$MPI_LINK_FLAGS:$MPI_LINK_FLAGS
  - echo $PATH
  - pip install -r requirements.txt
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; pip3 install -r requirements.txt; fi
  - mkdir build && cd build 
  - cmake .. 
  - make

