language: python
dist: trusty

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        packages: 
        - g++-7
        - hdf5-tools
        - python3
        - python3-pip
        - openmpi-bin
        - libopenmpi-dev
    env: COMP_EVAL="COMP_CC=gcc-7 && COMP_CXX=g++-7"
    python: 3.6

  - os: linux
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages: 
        - clang-5.0
        - g++-7
        - hdf5-tools
        - python3
        - python3-pip
        - openmpi-bin
        - libopenmpi-dev
    env: COMP_EVAL="COMP_CC=clang-5.0 && COMP_CXX=clang++-5.0"
    python: 3.6

  - os: osx
    osx_image: xcode10.1
    env: COMP_EVAL="brew update && brew install gcc@7 hdf5 open-mpi fftw fmt && COMP_CC=gcc-7 && COMP_CXX=g++-7"
    language: generic


before_install:
  - eval "${COMP_EVAL}"
  - export CC=${COMP_CC}
  - export CXX=${COMP_CXX}
  - $CXX --version


before_script:
  #install mpi (in linux)
  - export MPI="openmpi40"
  - echo "Running mpi installation script"
  - echo $MPI
  - echo $OS
  - mkdir -p $HOME/local
  - sh ./travis-install-mpi.sh $MPI
  - ls -r $HOME/local
  - export PATH=$PATH:$HOME/local/$MPI/bin
  - export LIBRARY_PATH=$LIBRARY_PATH:$HOME/local/$MPI/lib
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/$MPI/lib
  - if [ "$OS" = "Linux" ]; then export CC=mpicc; fi
  - if [ "$OS" = "Linux" ]; then export CXX=mpic++; fi
  - $CC --version
  - $CXX --version
  - mpicc --version
  - mpic++ --version
  #setup plasmabox
  - export PATH=${PATH}:/usr/lib/openmpi/include
  - export PATH=${PATH}:/usr/lib/openmpi/include/openmpi
  - export PATH=${PATH}:/usr/lib/openmpi/lib
  - echo $PATH
  - pip3 install -r requirements.txt
  - export PLASMABOX=$(pwd)
  - export PYTHONPATH=$PYTHONPATH:$PLASMABOX/corgi/lib
  - export PYTHONPATH=$PYTHONPATH:$PLASMABOX/lib
  - export PYTHONPATH=$PYTHONPATH:$PLASMABOX/python
  - export PYTHONPATH=$PYTHONPATH:$PLASMABOX/analysis
  - echo $PYTHONPATH


script:
  - mkdir build && cd build 
  - cmake .. 
  - make

