language: python
dist: trusty

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        packages: 
        - g++-7
        - hdf5-tools
        - python3
    env: COMP_EVAL="CC=gcc-7 && CXX=g++-7"
    python: 3.4

  - os: linux
    compiler: clang
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages: 
        - clang-5.0
        - hdf5-tools
        - python3
    env: COMP_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    python: 3.4

  - os: osx
    osx_image: xcode10.1
    env: COMP_EVAL="brew update && brew install gcc hdf5 fftw fmt && CC=gcc-7 && CXX=g++-7"
    language: generic


before_install:
  - eval "${COMP_EVAL}"

script:
  - mkdir build && cd build 
  - cmake .. 
  - make

